ckanSecretName: ckan-secrets
envVarsSecretName: ckan-env-vars

ckanOperatorImage: viderum/ckan-cloud-docker:cca-operator-v0.0.6
ckanImage: viderum/ckan-cloud-docker:ckan-v0.0.6
dbImage: viderum/ckan-cloud-docker:db-v0.0.6
solrImage: viderum/ckan-cloud-docker:solr-v0.0.6
nginxImage: viderum/ckan-cloud-docker:nginx-v0.0.6
solrcloudImage: viderum/ckan-cloud-docker:solrcloud-v0.0.6

# enabling this deploys a ckan release with only the infrastructure components
# these components are then shared between multiple ckan instances
# centralizedInfraOnly=true

# disable centralized infra. components
# solrDisabled=true
# dbDisabled=true

# disable the jobs service
# disableJobs=true

# enable this to deploy an instance which uses the shared infrastructure
# useCentralizedInfra=true

# the centralized infrastructure requires a unique id for each instance
# by default the current namespace is used but you can override it here
# ckanCloudInstanceId=ckan-demo-1

# connection details to the centralized infrastructure
# centralizedSecretName=
# centralizedSolrHost=
# centralizedSolrPort=
