ckanSecretName: ckan-secrets
envVarsSecretName: ckan-env-vars

# https://github.com/ViderumGlobal/ckan-cloud-docker/pull/19
ckanOperatorImage: viderum/ckan-cloud-docker:cca-operator-dd31fa561f8b70b9d2f6ca75bc16e0b716e11018
# https://github.com/ViderumGlobal/ckan-cloud-docker/pull/19
ckanImage: viderum/ckan-cloud-docker:ckan-dd31fa561f8b70b9d2f6ca75bc16e0b716e11018
dbImage: viderum/ckan-cloud-docker:db-v0.0.1
solrImage: viderum/ckan-cloud-docker:solr-v0.0.1
nginxImage: viderum/ckan-cloud-docker:nginx-v0.0.1
# https://github.com/ViderumGlobal/ckan-cloud-docker/pull/19
solrcloudImage: viderum/ckan-cloud-docker:solrcloud-dd31fa561f8b70b9d2f6ca75bc16e0b716e11018

# enabling this deploys a ckan release with only the infrastructure components
# these components are then shared between multiple ckan instances
# centralizedInfraOnly=true

# disable centralized infra. components
# solrDisabled=true
# dbDisabled=true

# disable the jobs service
# disableJobs=true

# enable this to deploy an instance which uses the shared infrastructure
# useCentralizedInfra=true

# the centralized infrastructure requires a unique id for each instance
# by default the current namespace is used but you can override it here
# ckanCloudInstanceId=ckan-demo-1

# connection details to the centralized infrastructure
# centralizedSecretName=
# centralizedSolrHost=
# centralizedSolrPort=
