{{ if .Values.useNginxIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ckan-ingress-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.nginxIngressMaxBodySize | default "1000M" }}
    {{ if .Values.enableGiftless }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /giftless;
    {{ end }}
{{ if .Values.nginxIngressExtraConfig}}{{ .Values.nginxIngressExtraConfig | indent 4 }}{{ end }}
spec:
  {{ if .Values.nginxIngressTlsSecret }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.nginxIngressTlsSecret }}
  {{ end }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: ckan
          servicePort: 5000
        path: /
      {{ if .Values.enableGiftless }}
      - backend:
          serviceName: giftless
          servicePort: 5000
        path: /giftless/
      {{ end }}
{{ end }}
