{{ if not .Values.centralizedInfraOnly }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: ckan}
spec:
  replicas: {{ .Values.replicas | default "2" }}
  revisionHistoryLimit: 2
  template:
    metadata:
      labels: {app: ckan}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/ckan-configmap.yaml") . | sha256sum }}
    spec:
      {{ if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{ end }}
      serviceAccountName: ckan-{{ .Release.Namespace }}-operator
      initContainers:
      - name: secrets
        image: {{ .Values.ckanOperatorImage | quote }}
        command:
        - bash
        - "-c"
        - |
          ./cca-operator.sh initialize-ckan-env-vars {{ .Values.envVarsSecretName | quote }} &&\
          ./cca-operator.sh initialize-ckan-secrets {{ .Values.envVarsSecretName | quote }} \
                                                    {{ .Values.ckanSecretName | quote }} &&\
          ./cca-operator.sh get-ckan-secrets {{ .Values.ckanSecretName | quote }} /etc/ckan-conf/secrets/secrets.sh &&\
          echo ckan secrets initialized successfully && exit 0
          echo failed to initialize, waiting 1 hour before exiting && sleep 3600 && exit 1
        {{ if .Values.useCentralizedInfra }}
        env:
        - name: CKAN_CLOUD_INSTANCE_ID
          {{ if .Values.ckanCloudInstanceId }}
          value: {{ .Values.ckanCloudInstanceId | quote }}
          {{ else }}
          value: {{ .Release.Namespace | quote }}
          {{ end }}
        {{ if .Values.centralizedSecretName }}
        - name: CKAN_CLOUD_POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.centralizedSecretName | quote }}
              key: "POSTGRES_HOST"
        - name: CKAN_CLOUD_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.centralizedSecretName | quote }}
              key: "POSTGRES_USER"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.centralizedSecretName | quote }}
              key: "POSTGRES_PASSWORD"
        {{ else }}
        - name: CKAN_CLOUD_POSTGRES_HOST
          value: db.ckan-cloud
        - name: CKAN_CLOUD_POSTGRES_USER
          value: postgres
        - name: PGPASSWORD
          value: "123456"
        {{ end }}
        - name: CKAN_CLOUD_SOLR_HOST
          value: {{ .Values.centralizedSolrHost | default "solr.ckan-cloud" | quote }}
        - name: CKAN_CLOUD_SOLR_PORT
          value: {{ .Values.centralizedSolrPort | default "8983" | quote }}
        {{ end }}
        volumeMounts:
        - name: ckan-conf-secrets
          mountPath: /etc/ckan-conf/secrets
      - name: files
        image: alpine
        command:
        - sh
        - "-c"
        - |
          chown -R 900:900 /var/lib/ckan && chmod -R ug+w /var/lib/ckan && chown -R 900:900 /etc/ckan-conf/secrets &&\
          ls -lah /var/lib/ckan && ls -lah /etc/ckan-conf/secrets
        securityContext:
          runAsUser: 0
        volumeMounts:
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: {{ .Release.Namespace }}-ckan}
        - name: ckan-conf-secrets
          mountPath: /etc/ckan-conf/secrets
      {{ if .Values.ckanSolrRebuild }}
      - name: ckan-solr-rebuild
        image: {{ .Values.ckanImage | quote }}
        command: [/ckan-entrypoint.sh, ckan-paster, --plugin=ckan, search-index, rebuild, -c, /etc/ckan/production.ini]
        env:
        - name: CKAN_STORAGE_PATH
          value: /var/lib/ckan/data
        - name: CKAN_K8S_SECRETS
          value: /etc/ckan-conf/secrets/secrets.sh
        - name: CKAN_K8S_TEMPLATES
          value: /etc/ckan-conf/templates
        - name: GUNICORN_WORKERS
          value: {{ .Values.ckanGunicornWorkers | default "2" | quote }}
        volumeMounts:
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: {{ .Release.Namespace }}-ckan}
        - name: ckan-conf-secrets
          mountPath: /etc/ckan-conf/secrets
          readOnly: true
        - name: ckan-conf-templates
          mountPath: /etc/ckan-conf/templates
          readOnly: true
      {{ end }}
      containers:
      - name: ckan
        image: {{ .Values.ckanImage | quote }}
        env:
        - name: CKAN_STORAGE_PATH
          value: /var/lib/ckan/data
        - name: CKAN_K8S_SECRETS
          value: /etc/ckan-conf/secrets/secrets.sh
        - name: CKAN_K8S_TEMPLATES
          value: /etc/ckan-conf/templates
        - name: GUNICORN_WORKERS
          value: {{ .Values.ckanGunicornWorkers | default "2" | quote }}
        ports:
        - containerPort: 5000
        {{ if .Values.ckanResources }}
        resources: {{ .Values.ckanResources }}
        {{ end }}
        volumeMounts:
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: {{ .Release.Namespace }}-ckan}
        - name: ckan-conf-secrets
          mountPath: /etc/ckan-conf/secrets
          readOnly: true
        - name: ckan-conf-templates
          mountPath: /etc/ckan-conf/templates
          readOnly: true
        {{ if not .Values.noProbes }}
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: {{ .Values.ckanReadinessInitialDelaySeconds | default "30" }}
          periodSeconds: {{ .Values.ckanReadinessPeriodSeconds | default "5" }}
          timeoutSeconds: {{ .Values.ckanReadinessTimeoutSeconds | default "10" }}
          failureThreshold: {{ .Values.ckanReadinessFailureThreshold | default "15" }}
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: {{ .Values.ckanLivenessInitialDelaySeconds | default "60" }}
          periodSeconds: {{ .Values.ckanLivenessPeriodSeconds | default "5" }}
          timeoutSeconds: {{ .Values.ckanLivenessTimeoutSeconds | default "10" }}
          failureThreshold: {{ .Values.ckanLivenessFailureThreshold | default "15" }}
        {{ end }}
      volumes:
      - name: ckan-conf-secrets
        emptyDir: {}
      - name: ckan-conf-templates
        configMap:
          name: ckan
      - name: ckan-data
      {{ if .Values.usePersistentVolumes }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-ckan
      {{ else }}
        hostPath:
          path: /var/ckan-cloud-{{ .Release.Namespace }}
          type: DirectoryOrCreate
      {{ end }}
{{ end }}