{{ if not .Values.centralizedInfraOnly }}
{{ if not .Values.disableJobs }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: jobs}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {app: jobs}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/ckan-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: ckan-{{ .Release.Namespace }}-operator
      {{ if .Values.ckanJobsTerminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.ckanJobsTerminationGracePeriodSeconds }}
      {{ end }}
      initContainers:
      - name: secrets
        image: {{ .Values.ckanOperatorImage | quote }}
        args:
        - get-ckan-secrets
        - {{ .Values.ckanSecretName | quote }}
        - /etc/ckan-conf/secrets/secrets.sh
        volumeMounts:
        - name: ckan-conf-secrets
          mountPath: /etc/ckan-conf/secrets
      - name: permissions
        image: alpine
        command:
        - sh
        - "-c"
        - |
          chown -R 900:900 /var/lib/ckan && chmod -R ug+w /var/lib/ckan && chown -R 900:900 /etc/ckan-conf/secrets &&\
          ls -lah /var/lib/ckan && ls -lah /etc/ckan-conf/secrets
        securityContext:
          runAsUser: 0
        volumeMounts:
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: {{ .Release.Namespace }}-ckan}
        - name: ckan-conf-secrets
          mountPath: /etc/ckan-conf/secrets
      containers:
      - name: ckan-jobs
        image: {{ .Values.ckanImage | quote }}
        command: [/ckan-entrypoint.sh, ckan-paster, --plugin=ckan, jobs, -c, /etc/ckan/production.ini, worker]
        env:
        - name: CKAN_STORAGE_PATH
          value: /var/lib/ckan/data
        - name: CKAN_K8S_SECRETS
          value: /etc/ckan-conf/secrets/secrets.sh
        - name: CKAN_K8S_TEMPLATES
          value: /etc/ckan-conf/templates
        - name: GUNICORN_WORKERS
          value: {{ .Values.ckanGunicornWorkers | default "2" | quote }}
        resources: {{ .Values.ckanJobsResources }}
        volumeMounts:
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: {{ .Release.Namespace }}-ckan}
        - name: ckan-conf-secrets
          mountPath: /etc/ckan-conf/secrets
          readOnly: true
        - name: ckan-conf-templates
          mountPath: /etc/ckan-conf/templates
          readOnly: true
      volumes:
      - name: ckan-conf-secrets
        emptyDir: {}
      - name: ckan-conf-templates
        configMap:
          name: ckan
      - name: ckan-data
      {{ if .Values.usePersistentVolumes }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-ckan
      {{ else }}
        hostPath:
          path: /var/ckan-cloud-{{ .Release.Namespace }}
          type: DirectoryOrCreate
      {{ end }}
{{ end }}
{{ end }}