{{ if not .Values.centralizedInfraOnly }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginxReplicas | default "2" }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: {{ .Values.nginxImage | quote }}
        ports:
        - containerPort: 8080
        {{ if .Values.nginxResources }}
        resources: {{ .Values.nginxResources }}
        {{ end }}
{{ end }}